//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM_EKZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkladTkani
    {
        public int Id { get; set; }
        public string IdTkani { get; set; }
        public string Kolichestvo { get; set; }
    
        public virtual Tkani Tkani { get; set; }
    }
}
