//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEM_EKZ
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazniyeIzdeliya
    {
        public int Id { get; set; }
        public int IdZakaza { get; set; }
        public string IdIzdeliya { get; set; }
        public string Kolichestvo { get; set; }
    
        public virtual Izdeliya Izdeliya { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
